services:
  - type: web
    name: bookit-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString
databases:
  - name: bookit-db
    databaseName: bookit
    user: bookit_user
    plan: free